import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { to, studentName, bookTitle, chapterTitle, score, total, percentage, passed, date, timeElapsed } = body;

  if (!to || !to.includes('@')) {
    return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
  }

  const formatTime = (s: number) => `${Math.floor(s / 60)}m ${s % 60}s`;

  // Use mailto as fallback (works without SMTP config)
  // For production, replace this with nodemailer + real SMTP
  const subject = encodeURIComponent(
    `Aviation Quiz Results — ${chapterTitle} — ${passed ? 'PASSED' : 'NOT PASSED'}`
  );
  const bodyText = encodeURIComponent(
    `Aviation Study Quiz Results\n\nStudent: ${studentName || 'N/A'}\nDate: ${date}\nHandbook: ${bookTitle}\nChapter: ${chapterTitle}\n\nScore: ${score}/${total} (${percentage}%)\nResult: ${passed ? 'PASSED ✓' : 'NOT PASSED ✗'}\nTime: ${formatTime(timeElapsed)}\n\nGenerated by FAA Aviation Study Quiz App`
  );

  const mailtoLink = `mailto:${to}?subject=${subject}&body=${bodyText}`;

  // If SMTP credentials are configured via env vars, use nodemailer
  if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
    try {
      const nodemailer = await import('nodemailer');
      const transporter = nodemailer.default.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT ?? '587'),
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });

      const htmlBody = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: ${passed ? '#16a34a' : '#dc2626'}; color: white; padding: 24px; border-radius: 12px 12px 0 0;">
            <h1 style="margin: 0; font-size: 22px;">Aviation Study Quiz Results</h1>
            <p style="margin: 4px 0 0; opacity: 0.85;">${passed ? '✓ PASSED' : '✗ NOT PASSED'}</p>
          </div>
          <div style="border: 1px solid #e5e7eb; border-top: none; padding: 24px; border-radius: 0 0 12px 12px;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555; width: 160px;">Student</td><td>${studentName || 'N/A'}</td></tr>
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555;">Date</td><td>${date}</td></tr>
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555;">Handbook</td><td>${bookTitle}</td></tr>
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555;">Chapter</td><td>${chapterTitle}</td></tr>
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555;">Score</td><td style="font-size: 18px; font-weight: 900; color: ${passed ? '#16a34a' : '#dc2626'};">${percentage}% (${score}/${total})</td></tr>
              <tr><td style="padding: 6px 0; font-weight: bold; color: #555;">Time</td><td>${formatTime(timeElapsed)}</td></tr>
            </table>
            <p style="color: #888; font-size: 11px; margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px;">
              Generated by FAA Aviation Study Quiz App. Based on FAA Public Domain Handbooks.
            </p>
          </div>
        </div>`;

      await transporter.sendMail({
        from: process.env.SMTP_FROM ?? process.env.SMTP_USER,
        to,
        subject: `Aviation Quiz Results — ${chapterTitle} — ${passed ? 'PASSED' : 'NOT PASSED'}`,
        html: htmlBody,
        text: decodeURIComponent(bodyText),
      });

      return NextResponse.json({ success: true, method: 'smtp' });
    } catch (err) {
      console.error('SMTP send failed:', err);
      return NextResponse.json({ mailtoLink, method: 'mailto', error: 'SMTP failed, use mailto' });
    }
  }

  // No SMTP — return mailto link so client can open it
  return NextResponse.json({ mailtoLink, method: 'mailto' });
}
